version: '3.8'

services:
  claude-mobile:
    build: .
    container_name: claude-mobile-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    restart: unless-stopped
    networks:
      - claude-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claude-mobile.rule=Host(`claude.yourdomain.com`)"
      - "traefik.http.services.claude-mobile.loadbalancer.server.port=8080"

  nginx:
    image: nginx:alpine
    container_name: claude-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - claude-mobile
    networks:
      - claude-network
    restart: unless-stopped

networks:
  claude-network:
    driver: bridge